\#Targets: prerequisites
#	commands
#
#
#Targets is the file(s) that is being created
#Commands is the steps taken to make the file (The actual code)
#Prerequisites are files that exist. Targets depend on prerequisite to work


